### ISSUE TITLE
unable to run exe of Edge Remover 2.0

### ISSUE THREAD

**Issue by caspertone2003** [jbara2002/edge-remover#14]
See
https://github.com/jbara2002/edge-remover/issues/13#issuecomment-1383020952

Thanks

**Comment by WindowsRefundDay** [comment]
Please refrain from making issues on other issues. Also what version of windows are you using. This can be found in Settings --> System --> About --> Windows Specifications --> Copy and paste it here.

**Comment by jbara2002** [comment]
Solved at:
https://github.com/jbara2002/edge-remover/releases/tag/2.1

**Comment by caspertone2003** [comment]
Issue not solved, but close item to avoid clutter

**Comment by jbara2002** [comment]
thanks for noticing..  maybe rewriting the verification of edge version is a good ideea for fixing.. 
normally i verified the executable version of edge and show it in the app.. when executable is not running , the app will return an error, or will not run.
