### ISSUE TITLE
MS edge is not removed on Win10 with updates from 2022-Oct-03

### ISSUE THREAD

**Issue by WayneSherman** [jbara2002/edge-remover#16]
"EdgeRemover.exe" v2.5 does not remove Edge on Win 10 Pro with Windows updates as of 2022-Oct or newer.  It does not remove Edge UWP on any of the version tested:

 Win 10 Pro 21H2 updated to 2022-May-03:  Edge is removed, Edge UWP is not removed
 Win 10 Pro 21H2 updated to 2022-Oct-03:  Edge is not removed, Edge UWP is not removed
 Win 10 Pro 22H2 updated to 2022-Dec-20:  Edge is not removed, Edge UWP is not removed

**Comment by jbara2002** [comment]
i can check by creating vms with updated versions and sayed by you..
Before publishing the script was tested with Windows 11 2xH2, Windows 10 20H1,20H2 and 21H2 updated at 7.01.2023.
So i will check and if that is an issue i will fix that.. but i can't promise much.

**Comment by jbara2002** [comment]
tested and fixed in 2.5.1
https://github.com/jbara2002/edge-remover/releases/tag/release2.5.1

**Comment by WayneSherman** [comment]
Tested new EXE version on Win 10 Pro 21H2 updated to 2022-May-03.

Get message "Edge Chromium is not installed".
Edge is not removed
Edge UWP is not removed

I have to unplug, so I will stop monitoring this thread.
