### ISSUE TITLE
Microsoft still installed 2023 April

### ISSUE THREAD

**Issue by SatisfactoryBug** [jbara2002/edge-remover#18]
After Reboot
I checked Desktop still have the Microsoft Edge ICON

I checked the Location Dir: C:\Program Files (x86)\Microsoft
Still show:
C:\Program Files (x86)\Microsoft\Edge
C:\Program Files (x86)\Microsoft\EdgeUpdate and in that folder / file
1.3.173.55
Download
Install
MicrosoftEdgeUpdate.exe

A shame but worth a try

I going to try the old way
install_wim_tweak
Microsoft Edge Chromium Blocker Toolkit

**Comment by jbara2002** [comment]
fixed in version 2.6.
