### ISSUE TITLE
 Windows 11 too ?

### ISSUE THREAD

**Issue by seba2282** [jbara2002/edge-remover#19]
Can't remove to end edge by exe. Stay integrated still files after Edge legacy, update edge chromium and that view edge. But only edge program chromium uninstalled.
I don't know too if put reg key to don't update edge key.
Is for Windows 11 too? Ot will plan?

**Comment by jbara2002** [comment]
its working in Windows 11.

**Comment by seba2282** [comment]
![IMG_20230515_213136412.jpg](https://github.com/jbara2002/edge-remover/assets/16944478/b14058d1-1202-469f-b552-2d3731132681)

![IMG_20230515_213156101.jpg](https://github.com/jbara2002/edge-remover/assets/16944478/3dd44e8d-6ff1-40f1-84c1-ca79687025eb)

On Windows 11 stay that edge as old, edge update and edge WebView after use your app to remove edge exe. 
That i told. I saw on windows 10 wasn't problems.

**Comment by jbara2002** [comment]
yes. as i can said on another GitHub Repos: i don't recommend tbe removal of EdgeWebView or another Webview Application because its used by some apps such Adobe or Minecraft Lancher for creating log-in window. So idk. about the Edge UWP, its working to create a new version, w/o gui and after double click is removing Edge and the Legacy Edge (UWP).

**Comment by seba2282** [comment]
What about other component? 
Edge update? Because he shouldn't sit if work your app. 
But i see still sit. 
So you will add function to remove Edge legacy, which sit after uninstall chromium, how i understood you good. I have right?

**Comment by jbara2002** [comment]
yes. you're right

**Comment by seba2282** [comment]
"Edge update"

That too will remove?
In next version?



"Adobe or Minecraft Lancher"

Why that use Microsoft WebView from Edge? I heard only widgets MS use, but i remove them mean app.

What about don't back Edge again after uninstall Edge? People blocked as some reg key in regedit. 

About that aspect too you took under attention ? 

Sorry if my asks are swag or bad.

**Comment by jbara2002** [comment]
yeah, kinda. In next version 2.6 it blocks edge downloading using EdgeUpdate, so after removing it will not reinstall Edge again.
And yes, it needed for creating browser window into app. I've use that with webview removed and it get some error. I've seen in microsoft's forum and it said the webview is neccessary. 
And yes. It used by Widgets, and Modern App of Microsoft Teams (in windows 11). If you don't know what is a webview you can check this link (https://en.wikipedia.org/wiki/WebView).

**Comment by jbara2002** [comment]
https://github.com/jbara2002/edge-remover/releases/tag/release2.6

**Comment by seba2282** [comment]
How you told "block edge update". So if i can understand stay edge WebView, but why to stay that "Edge Update" component? If it is only updater chromium edge? Or update something more else too? 
Or i understood you bad?

**Comment by jbara2002** [comment]
Edge Update has policies which can control what components are you updating (just like Google Update). So auto installing Edge is blocked by a policy check here (https://admx.help/?Category=EdgeChromium&Policy=Microsoft.Policies.Update::Pol_AllowInstallationMicrosoftEdge).
I'll keep EdgeUpdate for updating Webview.

**Comment by seba2282** [comment]
Thank you for information. You are great. You helped me:) 


I was have ask to you about one thing mean two apps. But i don't know if i can ask here. Maybe you know how help to remove them.

**Comment by jbara2002** [comment]
write here if you want

**Comment by seba2282** [comment]
Is app "wprowadzenie" (i don't know English name). There are all tips instructions how use windows 11. How remove that? I show i think when back in home. And how permanently remove that thing call chat in that windows 11, what download teams to windows 11?
