### ISSUE TITLE
Uninstall failed with exit code: 93

### ISSUE THREAD

**Issue by Tiagoquix** [jbara2002/edge-remover#8]

**Comment by jbara2002** [comment]
can you specify more details, about the error?

**Comment by jbara2002** [comment]
details including, the OS and how to get the error

**Comment by jbara2002** [comment]
so.. maybe trying applying my script with running with PowerRun by Sordum. It opens the script like SYSTEM User. https://www.sordum.org/downloads/?power-run

**Comment by WindowsRefundDay** [comment]
Actually the winget uninstall doesnt work properly
![image](https://user-images.githubusercontent.com/88746308/195952882-bb82029e-62e5-4412-abf8-5b3f7e75cdd2.png)
Heres an example of me running `winget uninstall microsoft.edge`

**Comment by WindowsRefundDay** [comment]
removed winget uninstall in #10. @Tiagoquix please go ahead and try it now.

**Comment by jbara2002** [comment]
I'll check the modified code soon. Also, if the winget is not exectuted or get error, (for me is working), it go to next variant(solution for uninstalling)
